[build]
target = "index.html"
dist = "dist"

# Features to enable for the WASM build
[build.features]
crate_features = ["hydrate"]

[watch]
watch = ["src", "index.html", "styles"]

[serve]
port = 8080
open = false
