mod dashboard;
pub mod deploy;
pub mod flakes;
pub mod install;
mod login;
pub mod machines;
pub mod nix;
mod not_found;
pub mod secrets;
pub mod services;
pub mod settings;

pub use dashboard::DashboardPage;
pub use deploy::{DeployProgressPage, DeployWizardPage};
pub use login::LoginPage;
pub use flakes::{AddFlakePage, FlakeDetailPage, FlakeListPage};
pub use install::InstallWizardPage;
pub use machines::{AddMachinePage, MachineDetailPage, MachineListPage};
pub use nix::NixOperationsPage;
pub use not_found::NotFoundPage;
pub use secrets::{AddSecretPage, KeysPage, SecretsListPage};
pub use services::{ServiceDetailPage, ServiceListPage, ServiceLogsPage};
pub use settings::SettingsPage;
